### ISSUE TITLE
CLI upgrade command

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#54]
### Describe the feature

This is an idea for the very future. After we merge #13 we could maybe introduce a `sidebase upgrade` command that keeps the existing files and attempts to upgrade the nuxt version and add any extra linting we introduced. 

I am not too sure how this would look on a technical level, but I think it would be awesome to add if possible!

**Comment by BracketJohn** [comment]
It should be possible, but with the current approach it is very hard to do: We would have to `diff` files and implement some sort of heuristic to not overwrite changes made by the user.

E.g., if the `database/index.ts` is modifified by the user _after_ they clone the repo, then we would have to surgically find and keep these changes (and somehow ensure that they are still valid with out changes!) when running `sidebase upgrade`.

The solution to this then rather is:
- convert more and more stuff into packages, so that we / users can run `npm i sidebase-packages@next` to upgrade
- use the nuxt theme mechanic, as I discussed with @pi0 and @atinux here https://github.com/nuxt/starter/pull/108#issuecomment-1248354155

**Comment by zoey-kaiser** [comment]
Sounds good! Thanks for your input. From what I understand this is something we can put onto our roadmap and keep in the back of our heads!

**Comment by BracketJohn** [comment]
yup! 🪨
