### ISSUE TITLE
New library ideas for sidebase

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/sidebase#56]
This is a thread in which developers can post their wishes for new libraries we can develop to enhance the experience of working with Nuxt3 and sidebase!

**Comment by zoey-kaiser** [comment]
## Tailwind-config-sync

### The problem
When developing today, you hardly stick to one front-end solution. From my experience I usually always work with TailwindCSS and at least one component library such as AntDesign-Vue or PrimeVue. One issue I have always run into was how to sync the colors and breakpoints of my Tailwind config and that of the component library. 
it always results in me defining my values in at least two separate locations, the Tailwind config and an extra SASS or SCSS file in which I can override the default values set by the component library. I find this very annoying and tedious as:
- You have two points of truth and must always update values in two locations
- Every component library has different names for their colors, making switching between them annoying as you always have to look into the documentation where and how to change the default colors
- Some component libraries require you to install extra packages to configure their colors (such as sass or scss) 
- You lose your overview of where you set specific colors

### The solution
My idea is to create a independent package that searches the Tailwind config for specific color keywords (such as `primary`, `secondary` etc.) If it finds these colors it detects the installed component libraries and automatically updates their themes to match the Tailwind config. 

We can also see if there are any other values that can be taken from the Tailwind config, such as breakpoints or border radius settings. 

In the end the goal is to extend the Tailwind config in such a way that component libraries can use its values. This makes it easier to change values, ensures all the config for design is in one location and the syntax is easy to read and customize. 

The exact technical details will need to be discussed as well as which frameworks we would initially support (as we would need to add them manually). However, I believe that this is a tool missing that many developers would love to see!

I would love to hear some feedback about my idea @BracketJohn @ineshbose @ReaperMaga @MaloLebrin and anyone else interesting in the topic!

**Comment by ineshbose** [comment]
Thanks for the mention @zoey-kaiser!

This is something I just worked on for an internal company project where I had to integrate the PrimeVue stylesheet with my Tailwind configuration - and to be completely honest, this had to be one of the most painful implementations I've had to do this year given that PV provides you a compiled 6000-line plain CSS file and that Tailwind also doesn't integrate with SASS (which I was hoping to use) as well as PostCSS. I'm still in progress of finishing this implementation, but I can tell you that I've spent about 40 hours on just this. If a package would've existed for this, my week would've gone so much easier, but having said all this, it makes me wonder about the feasibility of it since the entire stylesheet had to be refactored with manual logic. This was for PrimeVue however, and styling & configurations for different UI libraries could vary (like instead of having one CSS file, it could be isolated `<style>` blocks within the Vue component files). My other concern regarding this would be regarding the licensing of the UI libraries, since PrimeVue would only allow colour/SASS configuration through a paid version if I'm not wrong! I really like the idea but it's hard to say right now without looking into the practical logistics 🙂

**Comment by zoey-kaiser** [comment]
Hii @ineshbose!

Thank you so much for your insight! This was an idea I had today and I thought it might be worth looking into. I agree with you that it seems to be a lot of work and I also don't know how feasible the entire idea is. I personally have not worked much with PrimeVue yet, so your insight is really helpful! Thank you very much. 

My initial Idea came from working with AntDesign Vue which uses SASS for [theme customization](https://antdv.com/docs/vue/customize-theme) and it also allows you to do it in the free version. So it might make more sense to try it out on AntDesign for a V1. 

As for the issues with Tailwind. This is also something I had though about, so I was wondering if it might make more sense to create an entirely new config that exports specific values into the formats of different component libraries and TailwindCSS. this would allow us to have a list of variables that will then be correctly formatted into a [TailwindCSS color list ](https://github.com/tailwindlabs/tailwindcss/blob/master/src/public/colors.js#L10) and SCSS variables that are injected in the AntDesign SASS file. 

Obviously this is all still pretty loose and would need some testing, especially in the area of which component libraries would even be compatible.

**Comment by ineshbose** [comment]
The license linked is for PrimeVue (standard) itself which doesn't use SASS. Instead we're looking for the PrimeVue *Designer* for which the license is here - https://www.primefaces.org/designer/licenses. I could be wrong - this is what I was able to find and understand from using it!

**Comment by zoey-kaiser** [comment]
> The license linked is for PrimeVue (standard) itself which doesn't use SASS. Instead we're looking for the PrimeVue _Designer_ for which the license is here - https://www.primefaces.org/designer/licenses. I could be wrong - this is what I was able to find and understand from using it!

I see. Thank you very much!
